### PR TITLE
Add accounts resource

### PR DESCRIPTION
**Pull request by griffinmyers**

### CODE REVIEW

**Comment by danielmcgrath** [comment]
@griffinmyers Transactions is a [paginated resource](https://www.usebutton.com/developers/api-reference/#get-transactions) (see `res.meta.{next|previous}`) – with this implementation it's not possible to read beyond the initial 100 (i.e. most recent) transactions.

**Comment by griffinmyers** [comment]
@danielmcgrath oh cool.  alright let me think about how we should handle that.

**Comment by griffinmyers** [comment]
@danielmcgrath a couple ideas:

### 1

```javascript
client.transactions('acc-1', function(err, transactions, meta) {
  if (meta.nextCursor) { ... }
});
```

### 2

```javascript
client.transactions('acc-1', function(err, response) {
  if (response.meta.nextCursor) { ... }

  console.log(response.data)
});
```

(1) Could be done without breaking backwards compat
(2) Is more idiomatic, especially in the world of single-arity promise resolve handlers

I vote (2), obviously also exposing the `cursor`, `stateDate`, and `endDate` as optional parameters

**Comment by danielmcgrath** [comment]
Summarizing offline discussion: let's move toward the more idiomatic interface (option 2) and accept the major version bump as we're breaking compatibility.

**Comment by griffinmyers** [comment]
@danielmcgrath updated! 99e7433

**Comment by danielmcgrath** [comment]
Barring the one change, LGTM! Needs an update to the CHANGELOG as well.

**Comment by griffinmyers** [comment]
Thanks @danielmcgrath!

**Pull request merged**
